language: php
php:
  - 5.3
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install php5-sqlite
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
script:
  - phpunit test/