soundvenirs_homepage_index:
    path:     /
    defaults: { _controller: SoundvenirsHomepageBundle:Default:index }
    methods: [GET]

soundvenirs_homepage_upload:
    path:     /upload
    defaults: { _controller: SoundvenirsHomepageBundle:Default:upload }
    methods: [POST]

soundvenirs_homepage_qrcode:
    path:     /qrcode/{id}.png
    defaults: { _controller: SoundvenirsHomepageBundle:Default:qrcode }
    methods: [GET]

soundvenirs_homepage_download:
    path:     /download/{id}.mp3
    defaults: { _controller: SoundvenirsHomepageBundle:Default:download }
    methods: [GET]

soundvenirs_homepage_shortcut:
    path:     /s/{id}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: soundvenirs_homepage_download
        permanent: true
    methods: [GET]
