soundvenirs_homepage:
    resource: "@SoundvenirsHomepageBundle/Resources/config/routing.yml"
    prefix:   /

soundvenirs_api:
    resource: "@SoundvenirsApiBundle/Resources/config/routing.yml"
    prefix:   /api

soundvenirs_webapp:
    resource: "@SoundvenirsWebappBundle/Resources/config/routing.yml"
    prefix:   /app
