parameters:
#    soundvenirs_sound.example.class: Soundvenirs\SoundBundle\Example

services:
#    soundvenirs_sound.example:
#        class: %soundvenirs_sound.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
