parameters:
#    soundvenirs_sound.example.class: Soundvenirs\SoundBundle\Example

services:
    soundvenirs_sound.sound_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Soundvenirs\SoundBundle\Entity\Sound
