soundvenirs_api_sounds_retrieve_one:
    path:     /sounds/{id}
    defaults: { _controller: SoundvenirsApiBundle:Sounds:retrieveOne }

soundvenirs_api_sounds_create:
    path:     /sounds
    defaults: { _controller: SoundvenirsApiBundle:Sounds:create }
    methods:  [POST]
