parameters:
#    soundvenirs_api.example.class: Soundvenirs\ApiBundle\Example

services:
#    soundvenirs_api.example:
#        class: %soundvenirs_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    soundvenirs_domain.sound_repository:
        class: Soundvenirs\DomainBundle\Repository\Sound
        arguments:
            - @doctrine.orm.default_entity_manager
