parameters:
#    soundvenirs_domain.example.class: Soundvenirs\DomainBundle\Example

services:
    soundvenirs_domain.sound_repository:
        class: Soundvenirs\DomainBundle\Repository\Sound
        arguments:
            - @doctrine.orm.default_entity_manager
    soundvenirs_domain.soundlocation_repository:
        class: Soundvenirs\DomainBundle\Repository\SoundLocation
        arguments:
            - @doctrine.orm.default_entity_manager
