soundvenirs_webapp_homepage:
    path:     /
    defaults: { _controller: SoundvenirsWebappBundle:Default:index }

soundvenirs_webapp_appconfig:
    path:     /appconfig.js
    defaults: { _controller: SoundvenirsWebappBundle:Default:appconfig }
